### ISSUE TITLE
Picker control does not close [sometimes]

### ISSUE THREAD

**Issue by Nudelsieb** [ruhley/angular-color-picker#36]
Hi,

I am experiencing an issue within nw.js (node webkit) where the picker control sometimes does not close after the mouse has been clicked out side of it. In that case there is now other way of getting this done other than closing the window or destroying the element.

Did this occur before, any idea what might cause this? I suspect some internal event handling issue. 

One more bit of info: I am using the picker tool within UI-bootstrap accordions.

Thanks a lot.

**Comment by ruhley** [comment]
I have never used nw.js, are you able to share some code? That would help me greatly.

**Comment by Nudelsieb** [comment]
```html
<div class="form-group">
                                <label class="control-label col-sm-2">Stroke colour:</label>                                
                                <div class="col-sm-2">
                                    <color-picker ng-model="graph.stroke" color-picker-format="'hex8'" color-picker-alpha="false"></color-picker>
                                </div>
                            </div>
```

**Comment by ido567** [comment]
I have the same issue (and i'm not using the 'nw.js' lib)
Did you found the problem?

**Comment by ruhley** [comment]
@Nudelsieb @ido567 I cannot replicate your problem, so are you able to give me some environment information like OS, Browser, angular color picker version etc.

**Comment by Nudelsieb** [comment]
@ruhley my machine is Windows 7 64 bit and latest updates. nw.js uses chromium. According to the changelog (https://github.com/nwjs/nw.js/blob/master/CHANGELOG.md) it uses version 41.0.2272.76.

I don't know if this problem might be related to nw.js, but if @ido567 experiences the same issue and runs a different environment, then it may be a problem in color picker?

Thanks

**Comment by ido567** [comment]
I'v experienced the issue on both Windows and Linux (chrome and safari) 
I don't know what triggers it, but when the picker is stuck, nothing cannot remove it

**Comment by ruhley** [comment]
@Nudelsieb @ido567 Can you please uncomment [Line 365](https://github.com/ruhley/angular-color-picker/blob/master/angularjs-color-picker.js#L365) and try to reproduce it. If it is being hidden correctly you should see ```Color Picker: Document Click Event``` and ```Color Picker: Hide Event```.

The only thing that I can think might be causing it is this [if](https://github.com/ruhley/angular-color-picker/blob/master/angularjs-color-picker.js#L62-L65) not being run.

**Comment by ido567** [comment]
I made the changes you asked, next time I will post the logs next time I will have the issue

**Comment by Nudelsieb** [comment]
@ruhley will do so, thanks. I will let you know how it turns out.

**Comment by Nudelsieb** [comment]
@ruhley I got a log output while the problem occured. Basically it shows the correct event but nothing happens.

```javascriptColor Picker: Document Click Event
angularjs-color-picker.js:361 Color Picker: Hide Event```

Those two lines appear over and over every time I click somewhere on the document. however, the color picker is stuck and does not disappear!

**Comment by Nudelsieb** [comment]
@ruhley 
The log is as follows when the picker gets stuck.
```javascript
Color Picker: Document Click Event
Color Picker: Hide Event
```
Those two lines repeat over and over again every time I click in the document. However, the picker stays open.

Attached is also a screenshot.
![colorpicker_bug](https://cloud.githubusercontent.com/assets/12937991/11209385/a3a87264-8d18-11e5-82c3-36e961bfbdea.png)

**Comment by ido567** [comment]
Why did you close it? Did you fixed it?

**Comment by Nudelsieb** [comment]
@ido567 good point, didn't see it. I hope it's just a mistake ;-).

**Comment by Nudelsieb** [comment]
@ruhley I did. However, sometimes, when the picker gets stuck, there is no log.

I wonder about line 59: ```javascript
if ($scope.find(evt.target).length === 0) {
```

When you click the picker first this if evaluates to "true" and therefore fires "$scope.hide();". This shouldn't happen since at the same time you also fire "$scope.show();". If you have a timing problem in the event order then it may be possible that you set visible to false shortly after it has been set to true. I found in general, that the "$scope.hide();" fires every time I click something in the document. This can be any element, even buttons. You may need some more checks, say only fire hide if show has been fired before. I hope this makes sense.

**Comment by ruhley** [comment]
I have released ```v0.6.11``` which hopefully fixes your problem. Please tell me how it goes.

**Comment by Nudelsieb** [comment]
Awesome work, thanks. I will see how it goes. Do I see it right that scope.destroy was fired in some cases and removed the click event?

When will the version be available on bower? I still get 0.6.8.

**Comment by ido567** [comment]
Thanks! I'v updated the package, and will update if the problem will occur again

**Comment by ruhley** [comment]
Closing the issue now as I have not heard anything more. Feel free to open it again if the issue reappears.

**Comment by Nudelsieb** [comment]
So far I haven't noticed any problems, therefore many thanks for the fix, highly appreciated :).
